name: Bulk Create GitHub Issues

on:
  push:
    branches:
      - main

permissions:
  issues: write

jobs:
  bulk_create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bulk Create Issues
        run: |
          # Læs data fra CSV-fil (issues.csv), start fra anden række
          tail -n +2 issues.csv | while IFS=, read -r title body; do
            # Opret problem ved hjælp af GitHub API
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -d "{\"title\":\"$title\",\"body\":\"$body\"}" \
                 "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues"
          done
